latest_posts: Latest Posts
read_more: Read More
powered_by: Powered by %s
prev: Prev
next: Next
archive: Archive
about_this_post: About this Post
this_post_is_written_by: This post is written by %s
licensed_under: licensed under %s
home: Home
